services:
  php:
    image: tugboatqa/php:apache
    default: true
    depends: mysql

    # A set of commands to run while building this service
    commands:
      # Commands that set up the basic preview infrastructure
      init:
        # Link the document root to the expected path. This example links
        # /htdocs to the docroot
        - ln -snf "${TUGBOAT_ROOT}/htdocs" "${DOCROOT}"
        - sudo apt update && sudo apt install chromium chromium-driver

  mysql:
    image: tugboatqa/mysql

